[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.20"
via_ir = true
optimizer = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
polygon = { ley = "${POLYGONSCAN_API_KEY}" }