[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.20"
via_ir = true
optimizer = true
evm_version = "berlin"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }